#!/usr/bin/env bash
# Installs and configure web server to redirect

apt-get -y update
apt-get -y install nginx
sudo sed -i '/server {/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
	service nginx start
else
	service nginx restart
fi
