#!/usr/bin/env bash
# configure web server for error 404

sudo apt-get update
sudo apt-get install nginx
sudo touch /var/www/html/index.html
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo touch /var/www/html/404.html
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"

SERVER_CONFIG="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;

	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}
}"
sudo sh -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
