#!/usr/bin/env bash
# configure web server for error 404

sudo apt-get update
sudo apt-get install nginx
sudo touch /var/www/html/index.html
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo touch /var/www/html/404.html
sudo sh -c "echo 'Ceci n'est pas une page' > /var/www/html/404.html"
sudo sed -i '/server {/a error_page 404 /404.html;\nlocation = /404.html { internal; }' /etc/nginx/sites-enabled/default
sudo service nginx restart
