#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and say hi if count is 9

for (( i = 0; i < 10; i++ )); 
do
	if [[ $i = 9 ]]; 
	then
		echo "Hi"
		#statements
	fi
	echo "Best School"
	#statements
done
