#!/usr/bin/env bash
# Change nginx user to nginx 
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
