#!/usr/bin/env bash
# Change nginx user to nginx 
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
